### ISSUE TITLE
Implement a better routing solution for the website

### ISSUE THREAD

**Issue by alex-wilmer** [gatewaycash/gateway#10]
Why is the website not using a client side router? Or for that matter, why is it not saving view state in localstorage or something. The current setup causes any network interruption, crash or refresh to send the user all the way back to the startpage

react-router is defacto, though I'm a big fan of [reach router](https://reach.tech/router) since its api is easier and it's designed for accessibility -- something that should be very important to this project

again, something I'd be happy to do but that requires touching every file and maybe you have a good reason for this

**Comment by ty-everett** [comment]
No good reason, just me not knowing react fully yet :) please feel free to submit a PR for this, it would help a lot with UX

**Comment by alex-wilmer** [comment]
on it

**Comment by ty-everett** [comment]
Completed and deployed
