### ISSUE TITLE
Platform users should not be able to create platforms

### ISSUE THREAD

**Issue by ty-everett** [gatewaycash/gateway#108]
We don't want platforms within platforms, do we?

**Comment by dreamtrove** [comment]
why not? I mean marketplace.cash (which will happen) will have marketplace sellers, those sellers can have store pages, so maybe we do

**Comment by ty-everett** [comment]
True, but platforms by definition have users and commission rates. If each seller had a store where users could sign up and sell things on that particular store (paying commission to the store owner) this would be a valid use case, but when we add payment ID filters as a criterion for commission rules we can also do it that way.
