### ISSUE TITLE
move to yarn workspaces

### ISSUE THREAD

**Issue by alex-wilmer** [gatewaycash/gateway#11]
as this project grows, more and more modules will be written here. yarn workspaces provides the necessary setup for modules with cross concerns to be developed in the same repository.

I am of course happy to set this up

**Comment by lightswarm124** [comment]
do you mean mixing package-lock.json and yarn.lock or just use yarn.lock?

**Comment by alex-wilmer** [comment]
if we move to yarn workspaces, It would mean dropping package-lock, but this isn't about lockfiles.

https://yarnpkg.com/lang/en/docs/workspaces/

I'll take this one on

**Comment by ty-everett** [comment]
Instead of this we have separated into multiple repos to make things easier.
