### ISSUE TITLE
consider serverless architecture

### ISSUE THREAD

**Issue by alex-wilmer** [gatewaycash/gateway#12]
If this product scales, which would be great, we'll end up with major maintenance headaches. Before we go off the deepend and write a lot of serverside code we should discuss the idea of moving over to a serverless type of architecture.

There are a few main ways of going about it these days, but since the project is still small I *highly* recommend going the netlify route. https://www.netlify.com/

as long as the project remains open source we can host all our front end assets for free (with custom domains and tls + all that jazz) AND they act as the serverless hub for our open source functions of which they allow A LOT on the free tier

![image](https://user-images.githubusercontent.com/2880089/48879635-ae6f8e00-edda-11e8-9656-9f0079073648.png)

This would

- allow this project to run free all the way until it gets enough traffic to warrant revenue
- set us up for an easy transition to horizontal scaling when we actually need it. at which point we can reassess netlify for aws directly or hosting our own openfaas instance.

**Comment by ty-everett** [comment]
Netlify is live at http://clever-jennings-927820.netlify.com/
