### ISSUE TITLE
Callback URL Improvement

### ISSUE THREAD

**Issue by kosinusbch** [gatewaycash/gateway#13]
Since the current callback is being done by the users browser and contains no secret key, all a user would have to do is make a request to that API and they would get whatever they were purchasing free.

A alternative way of doing this is for you guys to monitor incoming transactions and then make a call to the API with a secret key that only you guy have access to, the button id, and the amount paid. This would make gateway.cash super useful for certain merchant applications.

Edit: This could also turn into something potentially monetizable for you where you offer the monitoring service in exchange for "premium" subscription on your site.

**Comment by ty-everett** [comment]
I apologize I haven't gotten back to this sooner. This is being worked on and it's in the plans. We never really ha callback URLs working and they were sort of just half-way built. Now that we've gotten more established things like this will be more clear in the future. Thank you for opening this issue.

**Comment by ty-everett** [comment]
Fixed in #54
