### ISSUE TITLE
server needs to use env vars for secrets etc

### ISSUE THREAD

**Issue by alex-wilmer** [gatewaycash/gateway#28]
Shouldn't be exposing secrets in github.

typical setup would be something like

- have a `.env.schema` file with keys and no values which gets checked into git

ie:

```
SQL_SECRET=
```

- put `.env` into `.gitignore`, `cp .env.schema .env` and fill in the values
- use `dotenv` npm package to load env vars into the code

**Comment by ty-everett** [comment]
Fixed during the repo reorganization chaos
