### ISSUE TITLE
basic nodejs tooling

### ISSUE THREAD

**Issue by alex-wilmer** [gatewaycash/gateway#29]
every nodejs dev environment at least has nodemon.

I suggest https://github.com/jaredpalmer/backpack

**Comment by alex-wilmer** [comment]
Personally I would take this much further. You're basically writing everything from scratch on the server.

You would get a lot more done with something like https://feathersjs.com/ without needing to buy into a convention style framework like rails or sails

**Comment by ty-everett** [comment]
Added nodemon to API and can be accessed wwith
```
npm run dev
```
Updates every time a file is changed, also option to use PM2 in production
