### ISSUE TITLE
Implement native currency support in the button and website

### ISSUE THREAD

**Issue by zander** [gatewaycash/gateway#3]
I expect that if I type "EUR" in the currency selection and press the demo button, that the popup shows me this selected currency.

What I get instead is this sentence;

> Send 1 Bitcoin Cash (BCH) to this address to complete your payment

**Comment by ty-everett** [comment]
Unfortunately, we haven't implemented this yet. We're working on this and it should be fixed soon. Sorry for the inconvenience.

**Comment by ty-everett** [comment]
Fixed in #54
