### ISSUE TITLE
Allow direct deposits to addresses using the gateway button

### ISSUE THREAD

**Issue by kosinusbch** [gatewaycash/gateway#35]
Since it is currently based on a userid system, you should instead follow moneybuttons philosophy and allow a optional address field so that the button could be used for other use-cases than just sending money to a single person. 

Imagine this being used as a tipping option on a user-generated content site, but instead of having to sign up their users could simply include their address on registration and tips would be paid to that through gateway.cash

**Comment by ty-everett** [comment]
I'm putting a bounty of 0.1 BCH from our donation address on this issue. ABC or SV, claimer's choice.

**Comment by ftrader** [comment]
Let's spice the pot.
I'll add another 0.9 (BCH or BSV) on top of that to bring the bounty to 1 (BCH or BSV), claimer's choice.
Paid independently by myself to address provided by claimer once @ty-everett approves the implementation for bounty release.
No conversion from BCH to BSV - you get 0.9 from me no matter which one you choose.

**Comment by ty-everett** [comment]
People were saying how 0.1 BCH isn't a big enough bounty, but they don't realize...this is only like 20 lines of code if that. It was $0.5 USD per ***line*** and now it's $5 per ***line of code*** to do this.

Clarifications:
```
<PayButton
    address="bitcoincash:pz3txlyql9vc08px98v69a7700g6aecj5gc0q3xhng"
    amount="0.1"
/>
```
and later on with the inject script { currently broken broken }
```
<script src="https://gateway.cash/pay.js"></script>
<div
    class="payButton"
    address="bitcoincash:pz3txlyql9vc08px98v69a7700g6aecj5gc0q3xhng"
    amount="0.1"
></div>
```

**Comment by ty-everett** [comment]
It's just a matter of changing payButton.js not to require merchantID or anything when address field is present

**Comment by ty-everett** [comment]
I just implemented this, as part of some larger changes. I decided to sacrifice the bounty in lieu of a more future-proof upgrade that desperately needed to happen anyways.

@ftrader feel free to shoot 0.9 BSV to our donation address, but since I'm the one who got this implemented it's not a big deal either way.

**Comment by ftrader** [comment]
Thanks for implementing this.
0.9 BSV sent to your donation address: `a9b15cbf160b99770c830b07680c29e2b104a42b2845a6c8667f39de02809c77`
