### ISSUE TITLE
Add support for .render()

### ISSUE THREAD

**Issue by Klakurka** [gatewaycash/gateway#58]
Add support for using a .render() function to generate a new Pay Button by passing in a div or div id and other parameters.

An example would look something like this:

`
payButton.render(document.getElementById('myPayButton'), {
  merchantID: "XXXX",
  amount: "5",
  currency: "USD",
  closeWhenComplete: "true",
  paymentCompleteCallback: function (response) { console.log("DONE"); }
}
`

This is a pre-req for our use case.

**Comment by ty-everett** [comment]
You can already use the pay.js inject script which looks for <div class="payButton"></div> on the page, but this is a good idea to attach the render function to the `window` object so it is always available, and to allow it to be called in the browser. I'll add this to pay.js now.

**Comment by ty-everett** [comment]
This has been fixed but hasn't been merged to master yet. I'll close this once it gets merged, but the fix is on rhw deonr-end branch so it might be a few days.

**Comment by Klakurka** [comment]
SG.

We should be able to get this live in one of our apps once it's in place.
