### ISSUE TITLE
Adding &includeUnpaid=NO to the /payments API endpoint causes it to run forever

### ISSUE THREAD

**Issue by Klakurka** [gatewaycash/gateway#78]
Adding &includeUnpaid=NO to the /payments API endpoint causes it to run forever and never return a result.

**Comment by ty-everett** [comment]
I'll look at this tomorrow

**Comment by ty-everett** [comment]
Not yet fixed

**Comment by ty-everett** [comment]
Fixed in `document` and on api.gateway.cash
