### ISSUE TITLE
Target div ID gets duplicated within itself when .render is triggered

### ISSUE THREAD

**Issue by Klakurka** [gatewaycash/gateway#88]
Target div ID gets duplicated within itself when .render is triggered.

Example (id=supporterPaymentButton):

`<div id="supporterPaymentButton"><div id="supporterPaymentButton" style="display: inline-block; padding: 0.25em;"><button class="jss27 jss1 jss12 jss13 jss15 jss16" tabindex="0" type="button"><span class="jss2">Pay with Bitcoin Cash ($240)</span><span class="jss46"></span></button></div></div>`

**Comment by ty-everett** [comment]
Looking into this now, thanks for reporting
