### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by ty-everett** [gatewaycash/gateway#98]
Responsiveness isn't quite done, and there are some slight tweaks and adjustments I'd suggest. `CreateButtonPage` is three panels wide on desktop and one wide on mobile, but there isn't a "middle ground" of two on medium screens. The same with the `Portal` page with the login info on it, and some other pages.

**Comment by ZacxDev** [comment]
This has been addressed in PR #117, re-open if further responsive changes are needed.
