### ISSUE TITLE
Two-tone design

### ISSUE THREAD

**Issue by ty-everett** [gatewaycash/gateway#99]
Currently, there is a lot of white in the design. What if we made the background color of the entire page #444 instead of #f3f3f3? It would then match the color of SourceCode and contrast with the white `Card` we're using for displaying content. We might find that the navigation bar would need to be dark in that case too, but a dark themed site might look cool too.

**Comment by ZacxDev** [comment]
@ty-everett You seem to have taken this one with the recent dark theme, assigning back to you.

**Comment by ty-everett** [comment]
Cool, I think we're good here for the time being, but can be re-opened when we get more resources
